version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diabetes-backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./diabetes-frontend
      dockerfile: Dockerfile
    container_name: diabetes-frontend
    ports:
      - "3000:80"   # ✅ Map browser port 3000 → container port 80
    depends_on:
      - backend
